Import pytorch package

In [1]:
import torch

Example 1 Simple Neuron (just 3 features)

In [7]:
inputs1 = [1.0, 2.0, -3.0]  # e.g., features from an engineering sensor
weights1 = [0.5, -1.0, 0.8] # Learned or predefined weights
bias1 = 0.1

Define vectors in the pytorch environment and perform $A*x+b$ (in this case, the result is a scalar)

In [8]:
inputs = torch.tensor(inputs1, dtype=torch.float32)   # test with float64 (pros and cons?)
weights = torch.tensor(weights1, dtype=torch.float32) # test with float64 (pros and cons?)
weighted_sum = torch.dot(inputs, weights) + bias1 # A*x + b (result is a scalar)
print(weighted_sum)
print(type(weighted_sum))
print("Weighted Sum (z): "+str(weighted_sum.item()))

tensor(-3.8000)
<class 'torch.Tensor'>
Weighted Sum (z): -3.8000001907348633


Apply activation function Rectified Linear Unit (ReLU), $\text{ReLU}(x) = \text{max}(0,x)$

In [9]:
output = torch.relu(weighted_sum)
print(output)
print(type(output))
print("Activation (ReLU): "+str(output.item()))

tensor(0.)
<class 'torch.Tensor'>
Activation (ReLU): 0.0


Apply activation function $\text{Sigmoid}(x)=\frac{1}{1+\exp{(-x)}}$

In [10]:
output = torch.sigmoid(weighted_sum)
print(output)
print(type(output))
print("Activation (Sigmoid): "+str(output.item()))

tensor(0.0219)
<class 'torch.Tensor'>
Activation (Sigmoid): 0.021881265565752983


Apply activation function to a n-size vector element-wise

In [11]:
n=5
input2=torch.randn(n)
output2_relu=torch.relu(input2)
output2_sigmoid=torch.sigmoid(input2)
print(input2)
print(output2_relu)
print(output2_sigmoid)

tensor([-1.8019, -0.6246,  0.1086, -2.3736, -1.4007])
tensor([0.0000, 0.0000, 0.1086, 0.0000, 0.0000])
tensor([0.1416, 0.3487, 0.5271, 0.0852, 0.1977])


In [12]:
x = torch.tensor([1, 2, 3, 4, 5])
print(torch.unsqueeze(x, 0))
print(torch.unsqueeze(x, 1))
print(torch.squeeze(x, 0))
print(torch.squeeze(x, -1))

tensor([[1, 2, 3, 4, 5]])
tensor([[1],
        [2],
        [3],
        [4],
        [5]])
tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


Example 2 Simple Neuron (multiple features = a set of training data)

In [ ]:
n=5
m=3
inputs2=torch.randn(n,m) # e.g., features from an engineering sensor (already tensor object)
weights2 = [0.5, -1.0, 0.8] # Learned or predefined weights (the neuron has its own weights)
bias2 = 0.0
print(inputs2)

tensor([[ 0.1160,  0.8226, -0.1007],
        [ 1.6801,  0.5424,  1.1243],
        [-1.3629,  0.5927, -0.6717],
        [-0.3678,  1.6269,  0.5863],
        [ 0.4247, -0.8231, -0.2747]])


In [ ]:
weights = torch.tensor(weights2, dtype=torch.float32) # test with float64 (pros and cons?)
weighted_sum = torch.mul(weights, inputs2) + bias2 # A*x + b (result is a scalar)
weighted_sum = torch.matmul(weights, torch.transpose(inputs2, 0, 1)) + bias2 # A*x + b (result is a scalar)
print(weights)
print(weighted_sum)
print(type(weighted_sum))

tensor([ 0.5000, -1.0000,  0.8000])
tensor([-0.8452,  1.1971, -1.8115, -1.3418,  0.8157])
<class 'torch.Tensor'>


In [ ]:
output3_relu=torch.relu(weighted_sum)
output3_sigmoid=torch.sigmoid(weighted_sum)
print(weighted_sum)
print(output3_relu)
print(output3_sigmoid)

tensor([-0.8452,  1.1971, -1.8115, -1.3418,  0.8157])
tensor([0.0000, 1.1971, 0.0000, 0.0000, 0.8157])
tensor([0.3004, 0.7680, 0.1405, 0.2072, 0.6933])
